# fly.toml app configuration file generated for seyoung4503-sapp3 on 2024-08-06T11:25:29+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'seyoung4503-sapp3'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8015
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
